provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  hallo:
    lang: go
    handler: ./hallo
    image: hallo
    secrets:
      - hallo
  slack-me:
    lang: python
    handler: ./slack-me
    image: alexellis/slack-me
    environment:
      write_debug: true
      read_debug: true
      content_type: application/json

