provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  hallo:
    lang: go
    handler: ./hallo
    image: hallo
    secrets:
      - fn-secrets
  slack-me:
    lang: python
    handler: ./slack-me
    image: alexellis/slack-me
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
      content_type: application/json
    secrets:
      - fn-secrets

  join-welcome:
    lang: python3
    handler: ./join-welcome
    image: alexellis/join-welcome:0.1
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
      content_type: application/json
    secrets:
      - fn-secrets
